#
# This is the server logic of a Shiny web application. You can run the
# application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
source("preprocess.R")
source("predict.common.R")
source("ngram.encode.R")
source("prepare.sb.R")
source("predict.sb.R")

# Define server logic required to draw a histogram
shinyServer(function(input, output, session) {
    observeEvent(input$randomSample, {
        textPrefix <- sample(test.sample, 1)
        updateTextInput(session, "textPrefix", value = textPrefix)
    })
    
    getReactiveTextPrediction <- reactive({
        textPrefix <- input$textPrefix
        predict.partial <- input$predictPartial
        n <- input$n.predictions

        if (nchar(trimws(textPrefix)) == 0) {
            NULL
        } else {
            sb.predict.text(textPrefix, predict.partial = predict.partial, n)
        }
    })

    output$predictionPlot <- renderPlotly({
        textPrediction <- getReactiveTextPrediction()
        if (is.null(textPrediction)) {
            return (NULL)
        }

        suffix <- paste(textPrediction$Suffix, "&nbsp;&nbsp;")
        score <- textPrediction$Score
        
        score.offset <- max(score) * 0.05

        p <- plot_ly(x = ~score, y = ~reorder(suffix, score), name = "Predicted Next Word",
                     type = "bar", orientation = "h",
                     marker = list(color = 'rgba(16, 52, 166, 0.6)',
                                   line = list(color = 'rgba(16, 52, 166, 1.0)', width = 1))) %>%
            layout(yaxis = list(showgrid = FALSE, showline = FALSE, showticklabels = TRUE, title = NA),
                   xaxis = list(zeroline = FALSE, showline = FALSE, showticklabels = TRUE, showgrid = TRUE, title = "Score")) %>%
            add_annotations(xref = 'x1', yref = 'suffix',
                            x = score + score.offset,  y = suffix,
                            text = round(score, 4),
                            showarrow = FALSE)
    })
    
    test.sample <- list(
        "No fatigue, or feeling ",
        "Curious fact is that 兔 is the Chinese character for rabbit and is pronounced “tu”, same as the English “to”, hence many Chinese who speak English liked to wish a happy new year by saying “Happy New ",
        "I am going to bomard you with detail photos later, but for now.. nighty ",
        "Local TV news drops the ",
        "Odell ",
        "I wanted to stay, from the bottom of my ",
        "I'll see them all tomorrow, but what brought the tears was thinking about how heartbroken I would be if ",
        "Then ",
        "I’m back to square one now, still looking for a ",
        "What would it look ",
        "BSL does not hold owners accountable for their ",
        "SCC: Caro’s imaginary ‘kill list’ in Rendez, and Rob’s similar one from the multistorey at the ",
        "Bean to all students who are taking a ",
        "small stairway area between living room and dining ",
        "My goal is to share my experiences and hopefully people will feel the same fullness and learn from the mistakes I’ve ",
        "Min 16: “I care very much what other people ",
        "Just lemme know and I'd be ",
        "Hence no one individual should be treated like a criminal until a court of ",
        "Read Mind Over Matter by Nora ",
        "Charlotte from Sugar Nellie and this is the ",
        "Night after night residents of the town guarded the house, and they are willing to swear that no ",
        "Because that's what ",
        "One year, after the Easter ",
        "“And ",
        "but few chocolate ice ",
        "... and no one gets ",
        "Trumble’s exceptional writing entranced me and ",
        "People think ",
        "In some cases it may just be a genetic thing, but ",
        "I woke up in the wee ",
        "Today I have a card to share with you all that I made using one of the newly ",
        "My clothes are starting to get a ",
        "If I were more into the puff sleeves or the funny flap alternatives, maybe ",
        "I know what kind of ",
        "Instructors can stick to one release from start to ",
        "He was standing with a close family friend and co-worker he'd known for almost 40 ",
        "One of the keynote speakers last ",
        "And many others that I may have forgotten along the ",
        "Barely two months ago, my grandpa – my Mini’s “Puppa” – was diagnosed with Acute Myelogenous Leukemia – and given a prognosis ranging from moderate to poor (depending on the treatment regime chosen and the response of the disease to it, of ",
        "For the past five months my ",
        "Okay, okay, I have been a horrible ",
        "As soon as ",
        "Thanks for reading, it means the ",
        "A Mom: high fructose corn ",
        "Hate the blog or Love the blog it is what it is real all the ",
        "On those rare ",
        "Unfortunately, I only appreciated half of the songs on this E.P which is saddening to say the ",
        "Not in the Monty ",
        "When I was little, ",
        "Let me ",
        "Throughout the entire book we hope that she survives the ruthless and cruel Hunger ",
        "Goldilocks has a backup name…The Big Bad Wolf, just in ",
        "The only thing that I can assure you is that no matter what happen, I will still cling to God’s will in my ",
        "Those salaries, particularly the latter, would be seen by many people as wonderful and I never took it for ",
        "Peonies seem to be holding their own, and we also have a bright pink plant that is doing great in here but admittedly, I have NO ",
        "As a Register feature reporter, I can’t tell you how many times I’ve wished to shine a light on someone’s book but haven’t been ",
        "John Michael Collins, 42, New ",
        "Thus it should come as no ",
        "I had two dreams this week and the first one was about getting fucked but ",
        "*This guide is in Eastern Standard ",
        "Vaswald George Hall, 50, New ",
        "As we all know, what happens in the US affects all of us, one way or ",
        "However Jim had already gone to bed and ",
        "In fact, in many ",
        "Me: Hey do you have any Goats for sale (Mind you he is a college student so of ",
        "Short term ",
        "I will be back in the morning, with my Totally Papercrafts DT card and it's my first ",
        "- double score lines top and ",
        "But he is actually turning 30 this ",
        "He allegedly threw several M&M's at a Des ",
        "The point of my story is I can't always post photos of all the ",
        "Diversity is a code-word for White genocide; anti-racist is a code ",
        "Looking back its clear its more than literally throwing out one thing every ",
        "When I was a senior in high ",
        "I can't wait to get home, and spend a few ",
        "Remember to post your projects using Inlinkz no later than 12:00 noon Central ",
        "So ",
        "The organization of my ‘blog’ will come together eventually, but for now its a melting ",
        "I am ecstatic that the Patriots made it to the Super ",
        "He may have his disreputable charm but he just isn't Sherlock ",
        "(For those of you who have not visited before- I have been intending to make one for the last 2 weeks but ",
        "It's so much ",
        "Steampunk is so hot right ",
        "Such an awesome way to start the new ",
        "I know that Bell's has become one of those rarefied American craft-breweries, and, yeah, yeah I know Two-hearted is the end-all-be-all of American IPAs, but I think Larry Bell may have drank a little too ",
        "And I have this horrible feeling that this is the last ",
        "Enoch had told the Southall Chamber of Commerce on 4th November 1971, “Yet it is more truly when he looks into the eyes of Asia that the Englishman comes face to ",
        "*If this actually ruins her ",
        "How many in South Africa and in the United States once attempted to pass for white in order they gain access to privileges denied them for no other ",
        "Only the sheriff’s ",
        "I am thankful for facebook which has allowed me to reconnect with long lost friends, or stay up-to-date with friends that I don't get to talk to as often as I would ",
        "Not just of the various critters that appear to be attempting to invade the house, but of a ",
        "That I’m happy doing what ",
        "Before I show the after photos, let's ",
        "And walked out with a brand ",
        "I had the honor of visiting the Cathedral at Wells the last time ",
        "The angels also told the women to go quickly and tell the disciples that Jesus Christ had risen from the ",
        "Except that anyone who expected just acoustic ",
        "When men and ",
        "I could not resist as it was humming through my ",
        "Avlon argues that independent bookstores still have an important ",
        "It was stressful for a few reasons; driving down toward Hartford and getting lost for an ",
        "If only she would understand that the world does not ",
        "I made it a couple of weeks ",
        "” I am sure, you wont come back again, so ",
        "Let me put it this ",
        "On Friday the National Portrait Gallery sent a ",
        "A spokesman for Defoe declined to ",
        "And not for me, the resources so often taken for ",
        "Still, Blumenthal's legislation is \"a ",
        "All lined up and ready to ",
        "Lynch said at a news ",
        "The neo-Nazi Golden Dawn has been considerably less successful: while younger Greek voters are deserting the Establishment in droves, they clearly have no desire to join the SS: in most areas it is at the lower ",
        "It came from a charting client of ",
        "I first started making them about 2 years ",
        "Reuters ",
        "I had been suffering with Shingles for months, and had been back to the surgery several times and just been given different painkillers, my weight had dropped by a stone and a half and I was so weak I could barely function, as I explained in a previous blog I was taking every high energy drink I could lay my hands on and pushed my glucose ",
        "PS Reiki peeps — vote early and ",
        "That way I ",
        "Add a small scoop of your powder (when you have made a few you will discover the joy of trying different combinations of coloured powders for different effects however for the most ",
        "Instead of frying the bean curd and yada yada, I just bought tofu puffs from my Pasar Segar (Fresh Market) and sliced in ",
        "Concept: On a high school science class field trip to a physics lab to witness an experiment, something goes horribly wrong and it looks ",
        "This content is provided “as is” and is subject to change or removal at any ",
        "The best way to find out about zines is through word of ",
        "How was she to find them when she did not ",
        "Alejandro Cordero, 23, New ",
        "It's one of the narrowest fjords in all of Europe, at one point it's only about 820 feet wide, and is a UNESCO ",
        "Not entirely ",
        "People can force themselves into thinking one way or ",
        "After the vision has been explained, God tells Ezekiel how he intends to accomplish the impossible, through the resurrecting power of the ",
        "We fell in love at ",
        "Guess is always a little bit over the ",
        "Let me know your ",
        "-Thank you for reading my interview with Northern Iowa LB LJ ",
        "Here are some of the photos I ",
        "I have been so ",
        "Something about outer ",
        "If you jump, nine out of ",
        "You must understand that it’s pretty normal that we all want the newest, best, shiniest, fastest, and brightest when it ",
        "She was taken to jail because a deputy clocked her doing 82 in a 40 mph ",
        "Every mother, especially, should keep a diary in which to note the successive phases of her child's physical, mental, and moral growth, with particular attention to the moral; so that parents may be enabled to make a timely forecast of their children's character; to foster in them every germ of good, and by prompt precautions to suppress, or at ",
        "It was monotone descriptions of things, usually some pun or two thrown into (like older geek from all walks of life seemed to love back then – more often than not based on Monty ",
        "Sorry for such a ",
        "But, because things are getting very involved around here and because it is what is going on with me and because I think this may help me to process all of the swirly mess that is my brain right ",
        "Flying Dog Brewery Double Dog Double Pale ",
        "My baby girl is 10 months ",
        "Sometimes they catch fire then fade ",
        "This is a birthday ",
        "Slowly whisk in the hot milk mixture into the cream ",
        "Rather than flitting and fretting about what may or ",
        "In a December 31 editorial column, the newspaper questioned the sentence imposed by a Cuban court on U.S. citizen Alan Gross, convicted of violating the ",
        "Attend the dinner and silent ",
        "Here's a \"Sweet\" Page to whet your ",
        "By this I ",
        "is the longest I've seen in my ",
        "I'd like to cook more, as I feel like I'm eating only a few different meals over the course of a week, but ",
        "I stroke her hair, feeling like the happiest man in the ",
        "I mean, it tastes delicious when it’s hot, but we had a really warm day and ",
        "All attendees will also be able to add on a three-day pass to the 16th Annual Electric Daisy ",
        "The Barr Trail up Pikes ",
        "I think! ",
        "Bring your “The Boy in the Striped ",
        "The approach to tasks, that I take for ",
        "Johannesburg - Zimbabwean-style land grabs will not happen in South ",
        "Kazuo Ishiguro’s Remains of the ",
        "story short: Burton can’t ask us to laugh at Barnabas’s reality for most of the film, and then suddenly attempt to turn Dark Shadows into a serious and consequential battle between good and ",
        "7) Spend time with pleasant people, kids, laugh hard when you get a ",
        "Reduce heat to low and when potatoes are ",
        "For months I have been trying to find an apartment in Paris to rent next ",
        "This painting is a revision on the original, completed three or ",
        "Oh well at ",
        "My mind, being at the mercy of its associations, rejects the ",
        "Maybe we ",
        "I got married later in 1999 and my husband and ",
        "I know ",
        "Allow to cool ",
        "This seems to imply that you have to be straight out of college to get this discount, but many dealerships allow you to get it as long as you’ve graduated in the past few ",
        "Then hubby was diagnosed with swine flu on New ",
        "‘It was a few months ",
        "I hope I have not been too confusing…..don’t worry if you don’t tell me about all of the things you did for extras, I will double check to make ",
        "Ink: Memento tuxedo black, rich cocoa, bamboo leaves, pear tart, cantaloupe, cottage ivy (Tsukineko), Copic ",
        "i will add in a little ",
        "A: I loved reading since ",
        "Talking to EA’s customer ",
        "Two, that you simply will not find any group of speakers of this calibre anywhere in the ",
        "The only time ",
        "For the rest of the day, and the next few weeks, Sean and ",
        "20 x 20 cm piece of fresh banana leaf, trimmed of brown edges, rinsed and patted ",
        "This is where your research will come into ",
        "Here’s hoping we have better ",
        "I am really ",
        "These are posts that made me ",
        "Endre beeing high on sugar after a birthday ",
        "I was doing a good ",
        "Though I've done a little bit better with this one, I wouldn't say ",
        "you've got blood and it tastes ",
        "The drugs' value was estimated at $5 ",
        ".....and it seems like such a long time ",
        "Original Air ",
        ".....and it seems like such a long time ",
        "We don't need to make another ",
        "Then i had a crab salad, two shrimps, 10 salmon sashimi, 5 tuna sashimi and 3 maki ",
        "Oh, and if you haven't guessed yet, yes, ",
        "Before I show the after photos, let's ",
        "The next day we headed off bright and ",
        "So I simply close the ",
        "I think it is a ",
        "10:42 a.m. — Heating 8.25 quarts of ",
        "A child dies from hunger every six minutes in southern Somalia, according to the United ",
        "Oh and as you ",
        "We spent the better ",
        "And every ",
        "Now let’s take the government of the United ",
        "Your situation with foster ",
        "and the mess is a death ",
        "It's not that ",
        "7 Stones to Shoulder @ 150/100# (or as close as ",
        "And whether they agree or ",
        "That advantage sometimes scares me as I wonder, how did I make it to where ",
        "Me and Bobby McGee by Janis ",
        "Names changed to nicknames for privacy ",
        "A recent story which my therapist narrated made me write this ",
        "Yes folks, that is 31 yr- ",
        "I have decided to shift the focus of my ",
        "Sheikh Sayeed made the comments in an ",
        "Original Screenplay: Woody Allen, Midnight In ",
        "And ",
        "one by Cornell Campbell got played a hell of a ",
        "And now I know what is Cinco De ",
        "Wednesday – the ",
        "That's great ",
        "Like I ",
        "Level 16: STR: +48, Increases your attack ",
        "BRIDGES CB, LIM W, HU-PRIMMER J, et ",
        "This one was taken from Jenny + David's pre wedding :) I've not been able to put up many photos from their session, as their wedding was just around the corner, but I thought I'd share this little behind the ",
        "Then, when ",
        "However, don’t expect me to be a fashion blogger, because ",
        "When someone asks God, into their heart they are considered (Baby Christians) This is a very tender time for a ",
        "Publishers must also learn to better embrace the most ",
        "Morbid as that was, I felt it was probably the best course of ",
        "Thomas Anthony Casoria, 29, New ",
        "So don't get your hopes up, we're talking Labour ",
        "Just like any other events, people started to talk less about the earthquake in ",
        "Provitamin D-2 – See Vitamin ",
        "Real estate agents are able to learn the secrets of the real ",
        "Roll on Thursday when I will finally get my butt into gear and get my exhibiton stock list together, ready for delivery to Rufford Gallery at the beginning of November and I might even ",
        "R3: *Sc 1, 2 sc in ",
        "So copylists are the only real ",
        "Farrell, 32, New ",
        "(Ralph Waldo ",
        "If you have been following my blog for a while, you will know that ",
        "But imagine what it’s ",
        "21-Aug 1970, Santa Monica Civic ",
        "4) I have not tested this recipe with natural peanut ",
        "google search terms; alternative + energy, renewable + energy, green + investments, clean + energy, united + states + energy, global + energy, middle + east + oil, alternative, renewable, energy, green+ business, wind + mills, wind + power, lithium + battery+ power, electric + cars, hybrid + cars, investment + bankers, green + business + funding, alternative + renewable + energy, alternative + energy+ inventions, biofuel, clean + fuel, solar + power, solar+ panels, green + stocks, ecology, eco, global + ",
        "- Hearing stories the next ",
        "But I do know that this is the first time in twelve ",
        "\"Pleasure is always at someone else's ",
        "He had worn 43 or 47 up until that ",
        "The nun I made this for said her favorite ",
        "But I may never see you again so ",
        "You are very aware of your ",
        "BLDGBLOG: Duct ",
        "I was sure she would push me out the door and say there was nothing she could do to ",
        "To be completely clear and pretend that I am refraining from cleverness: I’m writing about this, although ",
        "The city is experiencing sea-level ",
        "P.S Apparently 'cuppa' is an English expression too... so ",
        "But knowing this, you will better ",
        "We worked our way back and ",
        "Ah, and here it is deconstructed so that I ",
        "I think they would make a great ",
        "*Images: Hero Arts Very Merry ",
        "I cannot WAIT to ",
        "Some are exotic, such as recently added Lusaka, Zambia, and Vietnam’s Ho Chi Minh ",
        "The inaugural Denver Rare Beer Tasting is taking place in Mile High City during the annual Great American ",
        "More than anything I have done in the blog ",
        "The problem is that you, me, and everybody ",
        "I orginally started so I would have an outlet to process what had ",
        "At first I found the music to be somewhat annoying with its twangy vocals, but being musically curious as I have tended to be my entire ",
        "Myocardial ischemia is an intermediate condition in coronary artery ",
        "Now, you'll be able to sleep ",
        "Mississippi, and I looking up at the ",
        "As for the Catherines of the real world, people do have the capacity for change, no matter what David Chase might believe, and can end up being vital parts of your ",
        "Me: Well, you never know….so I get the house just in ",
        "Being a ",
        "The junkier the ",
        "Spray a large non-stick frying pan with low calorie cooking spray and place over a medium ",
        "The following day, beach events were cancelled due to the inclement weather, but the partying continued with a BBQ and house party, with lashings of food and ",
        "Let you know what ",
        "It has been so much fun to study this book.We have learned so ",
        "I was lacking enough purple to totally frame the text so ",
        "The folks at Hachette Books are the absolute ",
        "I hope this helps answer any ",
        "Anyway; if you read my previous post, I still do not have any good or ",
        "What I believe Disney is doing is making their menu items more pricey so people feel ",
        "If a caregiver and their loved one lives near a state border or spend a lot of ",
        "From the Huffington ",
        "Later, my youngest will play soccer, but that's all ",
        "After carefully placing the festive bunting in just the ",
        "Because in Sirah I learnt of war after war after war fought with everyone from Christians to nonbelievers, so when ",
        "Level 3: Mastery: +57%, Weapon ",
        "and we've met so ",
        "In short order the tables turn, and the mother becomes the wild, carousing one, now the embarrassment to her son instead of the other way ",
        "But not as you’d ",
        "I’m still wrapping my head ",
        "6 boneless, skinless chicken ",
        "Desperate times call for desperate ",
        "Last night I spent the majority of my ",
        "So they are going to cut my ",
        "That of ",
        "R1- ch2, 6sc in 2nd ch from ",
        "“It’s your own ",
        "Well ",
        "Over the weekend we entertained the ",
        "When our bean crop failed last ",
        "I didn't mean for it to be a couple of weeks between posts, but other mommy chores just kept getting in the ",
        "Fortunately, we weren't asked to vacate the ",
        "Filled with intriguing vintage photographs that are used in a clever way, it's unlikely you've come across anything quite ",
        "Lily of the Valley grew all behind my house when I was growing up and if I close my ",
        "It arrived in the ",
        "Starbucks is proud to join other leading Northwest employers in support of Washington State legislation recognizing marriage equality for same-sex ",
        "This doesn’t ",
        "Failure to disclose any information will render you liable to a fine of $50,000, or a week's worth of indenture to Donald ",
        "At this point, the audience rose to their feet and Gingrich received a standing ",
        "And don't ",
        "Managers, in a sincere desire to give their employees positive feedback, frequently tell employees they are “doing great” or that they “did a good ",
        "Dylan stands staring in my face at eye ",
        "Rejection and self-pity have been told to ",
        "I just ",
        "Now I've made up my ",
        "The politician has the power to accept or ",
        "Four-leaf ",
        "I thank the puffed-out linebacker and move on to my last few interviewees, maintaining eye contact, getting the job ",
        "Mayors, county commissioners and others who took part in a discussion of the ",
        "\"It's one small step in the ",
        "\"We're not talking about a family who is renting an ",
        "Gordon, executive director of New ",
        "West Philadelphia abortion doctor Kermit Gosnell routinely delivered live babies in the third trimester of pregnancy, then murdered them by \"sticking scissors into the back of the baby's neck and cutting the spinal ",
        "øUnion Rags, an agonizingly close second to Hansen in the 2011 Breeders' ",
        "For more information, ",
        "Thomas hesitated and passed to Jamal ",
        "NEW YORK -- Detroit Tigers left fielder Delmon Young was ",
        "NAIA championships: Concordia has taken 34 athletes to the NAIA championships, which begin Thursday at Indiana Wesleyan ",
        "This spring, Bochy said he would take the decision of blocking the plate out of Posey's hands because, \"I certainly don't want people to ",
        "One San Francisco officer was injured during the incident and was treated at a ",
        "Each participant is encouraged to raise at ",
        "You can start your own ",
        "“The possibility of a violent encounter, this time with law ",
        "The short survey contains eight, mostly multiple choice ",
        "Sure, this was consumer culture, but it felt ",
        "San Clemente will ask the federal ",
        "George ",
        "Both ESPN and the NFL Network have termed Leinart's eventual arrival as the backup quarterback to Carson ",
        "It's so much a ",
        "Bautista coats prawns ($11) in paprika, garlic and a splash of sherry, and pairs mussels and clams ($12) with garbanzo beans, bits of andouille ",
        "Rangers, NBC ",
        "\"It was one of the best coaching jobs I have ever seen, and as a ",
        "But the challenge made it that ",
        "Then one day ",
        "\"It's amazing, the fans, it's like always,\" said Fernandez, who made 3 of 8 field goals and had nine ",
        "\"Over the last decade, seven local hospitals have closed and our residents rely heavily on UMDNJ for their primary and emergency health ",
        "In September 2010, the CIA began to zero in on a heavily secured, three-story compound on a dirt road in Abbottabad, ",
        "All of this creates a plausible denial that a decision has been ",
        "The painting \"embodies Klein's obsession with the irreconcilable concept of presence and absence, life and death,\" said Loic Gouzer, Christie's post-war and contemporary ",
        "Manning drops back to pass, and Vince Wilfork and Rodney Harrison (who unretired and was signed to a free agent revenge contract minutes before kickoff) burst through the offensive line, each with a clear shot at Manning for a game-winning safety, when both are distracted by the Lucas Oil ",
        "Their banks own a lot of the government debt of Spain and ",
        "But he broke out in a big ",
        "District trustees have given preliminary approval to $28 million in budget ",
        "Vanecko, who showed up for a police lineup with criminal-defense ",
        "The Farmers capped off a share of the Class 4A Mountain Plains League title with a 13-1 season under first-year ",
        "No ",
        "Cole rolled his ",
        "Or that individuals who have worked for decades in the legal ",
        "Tanner Andrews, Greco-Roman 74 kg  ",
        "Where are you ",
        "Rather than putting on a suit and hanging out backstage - for who knows how ",
        "I fly on Continental a ",
        "With a city hearing officer's decision Thursday affirming the denial of a march stepping off from Daley ",
        "The Willamette women's basketball team canceled its scheduled game Tuesday against Corban College and its games Friday and Saturday at the Oregon Institute of Technology Tournament in Klamath ",
        "1/3 cup sour ",
        "Jon ",
        "\"My heart goes out to everyone and their ",
        "A law professor at the Center for the Study of Law and Religion at Emory University in Atlanta, says the Supreme ",
        "Police ",
        "RF Brian Heere (.246) and LF LeVon Washington (.209) each had two ",
        "The fiscal year 2013 Energy and Water Appropriations bill is expected to be approved by the full ",
        "But a late-season resurgence, including a 12-5-3 record in the 20 games Toews has missed, has seen the Hawks pull within striking ",
        "Toni Malone's towering burgers may be the most ambitious in all of Los ",
        "Before Ohio gives a lot more public money to privately run charter schools, it has to do a better ",
        "Wolstein's departure does not change anything about Developers Diversified, said Alexander Goldfarb, a senior real estate investment ",
        "Cynthia Carpathios lives in Northeast ",
        "Then the Phillies broke a 2-2 ",
        "Sacramento's Isaiah Thomas was named the Western ",
        "That drew a sharp response from Dustin Pedroia before Monday's 1-0 loss to the Tampa ",
        "\"I think I could swallow this case one way or the other but ",
        "With a break in the action, it seemed fitting to take a ",
        "Cue escalating blood ",
        "Why go: To support a ",
        "I’d rather talk about my new show, which will document my ",
        "Authorities are looking for a suspected Hawaiian Gardens gang member who allegedly poured flammable liquid on his girlfriend and set her on ",
        "The bride-to-be is employed by SSM DePaul ",
        "Board of Chosen Freeholders Caucus, May 22, Freeholders’ Assembly Charter, third floor, Hudson County Administration Building ",
        "A: Gun tax to pay for mental ",
        "Refunds are expected to average about $500 — slightly more than last ",
        "The case centers on a 2008 summer fundraiser in Port Sanilac for a volunteer fire ",
        "What we've done so far is some minor miracles, and we hope to get this project off the ",
        "USC received $40,000 to help it produce an online video game based on the writings of Henry David ",
        "The 2008 NFL Defensive Player of the ",
        "If refrigerated, bring to room ",
        "Nutrition information per serving (values are rounded to the nearest whole number): 220 calories; 70 ",
        "“We want to create an ",
        "Big Brothers Big Sisters of Orange ",
        "For the record, Jesuit took home the 6A boys basketball title for the fourth year in a ",
        "The Cleveland voucher program was the first school voucher program in the state of Ohio and only the second school voucher program in the ",
        "They are armed with hundreds of millions of ",
        "AUBLE RETIRING: Veteran reporter John Auble is handing over the microphone after 23 years at KTVI ",
        "“The Boston Herald is more popular than ever — 2.6 million unique visitors to our website and 1.3 million reading the print ",
        "\"This will be a test of their sincerity; they're not ",
        "\"We’ve put out tens of thousands of dollars every month with the hopes that the program could be up and running,\" he ",
        "\"The case was not investigated any further because detectives concluded there was insufficient evidence to ",
        "“But being older, being him, being a running back and that mentality, you know that’s the ",
        "It was all out of my control,\" Randle ",
        "\"As soon as I became a teenager, I became promiscuous, but at the same ",
        "\"The album finds us moving into a direction of more a band effort than the first disc, 'Capgras,' \" said Fleisher, a 2000 Lake Catholic High ",
        "The new questions over the tunnel’s cost come in the wake of reviews by the FTA of other high-profile New ",
        "Tim Grendell, a Chesterland Republican, who has used a steady stream of statistics about water flowing in and out of Lake ",
        "But when I returned to Rome for Christmas, I was surprised to realize that what ",
        "Overall, high school graduation rates in New Jersey decreased an average of 9 percent in 2011 compared with the previous ",
        "PROPERTY DAMAGE: On March 1, a 23-year-old resident of the 100 block of Oakwood Drive, Collinsville, was arrested on the ",
        "The foundation also offers respite in beach and mountain areas on the East ",
        "District Judge Susan ",
        "Wood laughed and said he was a ",
        "The hunter who fired the ",
        "24grille at Westin Book Cadillac: Every mom will receive a ",
        "The Blue Angels already have their 2013 schedule planned as well with shows in Key West, Tampa's MacDill Air Force Base and returns to Pensacola ",
        "Saturday night's blaze at the Longport Boulevard pier marked the second ",
        "Jason Arnott scored a power-play goal with 9:54 to to in the second period to ",
        "Pau Gasol had a triple-double with five minutes to play in the third ",
        "Obama's visit around the anniversary of bin ",
        "The focus of today's speech, Quinn's administration has said, will be about education, economic development and \"jobs, jobs, ",
        "\"By opening the door to long-haul trucking between the United States and Mexico, America's third largest trading partner, we will create jobs and opportunity for our people and support economic ",
        "\"We looked at that 20 years ago, developing a rail ",
        "\"There are so ",
        "“We continue to game-plan for Roy as an All-Star player because he’s capable of doing that on any night,” Carlisle ",
        "When it's complete, the mural will be emblazoned with the phrase \"What you do in life echoes into eternity,\" a phrase Ferrick hoped rang true for the mural, too, she ",
        "in the August killing of a woman in the parking ",
        "An annual TriMet audit released last ",
        "I think he's averaged one isolation play per game in this ",
        "The only downside, said sophomore Brandon Spruill, is the possibility that the Nov. 26 football showdown with the Kansas Jayhawks in Arrowhead Stadium could be the last ",
        "1/3 cup finely ",
        "The area where the BP well sits is on the continental slope, formed by millions of years of deposits from the Mississippi ",
        "In making her decision, Guadagno ",
        "\"Baker Hughes will likely come under fire for not closing on this deal when BJ Services was much cheaper,\" Curran ",
        "But Santorum addressed the comment during an ",
        "If you're going to pick up litter by a waterway, remember that factory-farm runoff is a leading source of water pollution and opt for a vegan lunch, such as a veggie ",
        "Louis a little more than a ",
        "BSkyB defended itself as it reported a 19 percent ",
        "It would mean a ",
        "Crescent ",
        "Note: Teams selected by Jeff Seidel after consultation with The Baltimore ",
        "Brown sat alongside state Senate President Pro Tem ",
        "An Obama campaign web video soon followed, including a quote from a 2007 Romney interview in which he said it was not worth \"moving heaven and earth spending billions of dollars just trying to catch ",
        "This home is ",
        "The attorney general advised consumers to ask for written information before making donations to any charity and to avoid giving credit or ",
        "Twice in the past five years, odors have raised alarm in Northern New Jersey and New ",
        "\"I was being trained while waiting, but didn't realize it,\" he ",
        "\"But the fact is he gets the work ",
        "I mean, in terms of baseball marketing and public ",
        "Regina Spektor, \"All the Rowboats\": Life is but a ",
        "\"People are in favor of home rule, but at the same ",
        "The former senator from North Carolina pleaded not guilty to six ",
        "\"The girls wanted this game badly enough, we were at home and the girls did a better ",
        "øThe crowd cheered wildly when Bolt won in his first 100 of the year, giving him a standing ",
        "\"I'm just 4-foot-8 and 82 ",
        "-- Junior running back LaMichael ",
        "Feb. 18—x-Budweiser Shootout, Daytona Beach, ",
        "The Arizona Department of Public Safety is looking for a potentially dangerous gang member who was bonded out of Pinal County Adult Detention ",
        "He would have lost a third if his ",
        "In second ",
        "A cursory glance at Twitter indicates much of the American public enjoyed her sanitized, stilted cover of the “Skinny Love,” and if that’s the ",
        "Still others relate stories of coming to the game on light rail from Folsom and on Amtrak from Davis and having dinner beforehand at one of the dozen or so new restaurants within walking ",
        "I said out ",
        "Stephen Gregory Nagy, 49, was arraigned Thursday afternoon on 24 counts, including criminal antitrust, racketeering, first-degree theft, obstructing governmental administration, tampering with ",
        "Analysts surveyed by Thomson Reuters, on average, expected profit of 37 cents per share, on ",
        " Fix water-wasting problems in your irrigation ",
        "They are livid at the thought of having to pay higher ",
        "The organization also met in St. ",
        "That's all great, but here is the reality: Los Angeles is still five games under .500 and 6 1/2 games back of the Texas ",
        "Obama would be wiser to argue that a more activist government has made it easier for one generation to endow the next by providing benefits like student loans, the GI ",
        "And he, unlike Alvarez, has no power to convene a grand ",
        "For reservations, ",
        "It was only the next ",
        "Shanthi was a gift from Sri ",
        "\"You want to pass these memories on,\" said Hensel, a retired battalion fire chief who fled his home at 1110 Fairmont Drive on Sept. 9 after prying ",
        "It’s about seeing the mist coming off the lake early in the ",
        "\"Once you cross the six-figure mark, you think, what's a few thousand ",
        "Launched last year, the program has made roughly $440 ",
        "Please cast your ",
        "Questionable Calls: The Colts are in the process of converting to a 3-4 scheme under new head coach Chuck ",
        "Approximate values per serving: 700 calories, 330 calories from fat, 37 g fat (19 g saturated, 1 g trans), 265 mg cholesterol, 44 g carbohydrate, 46 g protein, 5 g fiber, 560 mg sodium, 48 ",
        "427-A Swift St., Santa ",
        "He also ",
        "Nutrition information per serving (values are rounded to the nearest whole number): 340 calories; 160 calories from fat (47 percent of total calories); 17 g fat (5 g saturated; 0.5 g trans fats); 75 mg cholesterol; 19 g carbohydrate; 25 g protein; 3 g fiber; 670 ",
        "Since that note was prepared, House Veterans Committee Chairman David Day, R-Dixon, pared back the amount of ",
        "Touhill Performing ",
        "Context: While the freshness and soft tannins of the cabernet franc invite sipping on its own, McKenna also enjoys it with grilled steaks, sausages, barbecued ribs, lamb, meatloaf, roast chicken, mushroom bruschetta, mushroom soup, French onion ",
        "Dinner main ",
        "They won three in a ",
        "The rebel-held city in western Libya has been under siege for several weeks by forces loyal to Libyan ",
        "» Tuesday night: Mostly cloudy, with chances of showers and ",
        "\"I just said there was not enough ",
        "\"The vast ",
        "Sowell's defense against the death penalty painted him as a victim of childhood abuse suffering with post-traumatic ",
        "Wolstein Center – Cleveland State ",
        "With the score tied 52-52, and fortunate that Houston freshman Alvin Franklin had missed the front ",
        "Because while Blazers were getting what McMillan called \"manhandled\" on the boards, the centers were absent as Marcus ",
        "Analysts expected Wynn to report quarterly profit of 71 cents per ",
        "Skylar Diggins had a triple-double and Notre ",
        "Kroger met with the governor's task ",
        "The family recently talked with The Associated ",
        "ceremony brings $130 million into Los ",
        "We want to go out here and give them a show and give them what they ",
        "Pasadena (10-7) ends league play 2-4 and likely needs a strong run through the Pacific League tournament to net a CIF Southern ",
        "The Lost Years, by Mary Higgins ",
        "1528 NW 127th Ter; 2,379 ",
        "Tuesday afternoon, members of the House of Representatives rose one by ",
        "One piece compared the Depression-era \"Hooverville\" libraries to the book collectives that popped up at Occupy encampments last ",
        "Coach of the year: Jim Schottmueller, McCluer ",
        "\"Everyone out there loved him,\" Horton ",
        "Measure B, as it is designated, would reduce pension benefits for new hires and require current workers to ",
        "Attorneys for the plaintiffs say Countrywide Financial had all their clients' financial information including mortgage information, credit card, and Social Security ",
        "Here are the words the winners chose to ",
        "Apparently, the GOP is determined not to ",
        "Britney Obstar, a 30-year-old former Portlander now living in Vallejo, Calif., was ordered to pay full restitution to Adidas and serve three years of supervised ",
        "And that is what it means to be a San ",
        "New Jersey Transit Police and Rutgers ",
        "\"What the FTA has pretty ",
        "2 cups shredded sharp Cheddar ",
        "When Pat Melville placed her land into a program to ensure that no development can occur on it, she created a milestone for a local nonprofit ",
        "It’s not looking ",
        "14429 NE Beech St; 2,821 square ",
        "The honor roll recognizes student journalists who have excelled and have a grade-point ",
        "The official spoke on condition of ",
        "Monday: Mostly sunny, with a high ",
        "He was a combined 15-of-44 in the first two games of the series, although he had a game-winning jumper with 1.5 ",
        "That process typically takes three to ",
        "Inge's big bat backed Tommy Milone (5-2), who struck out six in seven innings to win for the fourth time in ",
        "Net income for the three months ended Dec. 31 increased to $25.2 million, or $1.12 a share, from $23.4 million, $1.05 a share, in the same period a ",
        "Past audits did not check response times, Yost ",
        "The 6-3 wing led the area in scoring at 23.1 points per ",
        "Pending: 2, average price is $324,900; 1,476 square feet or $220.12 per square ",
        "Q: Considering those who have played high Class A or higher, which position players do you ",
        "$85 billion in aid for state and ",
        "As for Maldonado's Democratic rival this fall, San Francisco Mayor ",
        "\"We just pulled it together,\" Turner ",
        "Asked if he’s \"good\" with Miller -- who will be inducted into the Basketball Hall of Fame in September -- James said, \"I’m good with my ",
        "She was doing a revival of \"Sweet Charity,\" having played San ",
        "So did the Ohio Department of ",
        "On the eve of The Kentucky-Kansas Big One, he sounded like the anti-Vince ",
        "Among public school students in grades one through three, 22 percent are Latino, 5 percent are Asian American, 3 percent are African ",
        "Experts will offer tips on how to sort through and organize items, selecting a real ",
        "\"Maybe here,\" Urszula said a few minutes ",
        "Stepp said he believed the threats are an aftermath of the incident at Chardon High ",
        "Holder Jr., in testimony Tuesday before a House appropriations subcommittee, said the Department of ",
        "\"When you talk to an investment bank these days, they'll tell you that a company on track to generate $75 million to $100 million over the ",
        "18100 block of Irvine Boulevard - 7/8 - Petty ",
        "City officials said the purchase of the Coldwell ",
        "\"That's exactly what went through my ",
        "Commissioner Roger Goodell was on hand, along with New ",
        "\"Nothing would make me happier because the guy can really sing,\" Bacharach told The ",
        "University Center for the ",
        "North Brevard Funeral ",
        "1½ cups grated Monterey Jack ",
        "That's why the agency is under fire in some quarters for outsourcing many Occupy-related misconduct cases, including the near-fatal wounding of Iraq war ",
        "Johnson began running for president as a Republican and is now seeking the Libertarian ",
        "This is about them, Calipari ",
        "Calories 135 Fat 5 g Sodium 226 ",
        "Department of ",
        "The sources spoke on the condition of anonymity because they were not authorized to ",
        "Here's Angelina's best attempt to articulate the split: \"It's just too ",
        "Higham considered his most important works to be \"Trading With the Enemy\" (1983) and \"American Swastika\" (1985), which examined collusion between the Third Reich and prominent Americans during World War ",
        "ø\"It's a blessing to be part of a group of guys who want to work every ",
        "North Hunterdon is looking good in North Jersey 2 Group 4, but will probably have to dispose of pesky Watchung ",
        "The film, based on a 2008 novel in which children fight to the ",
        "\"This day is always tough, coming in, getting stuff out of your locker,'' said Panthers defenseman Ed Jovanovski, 35, the only active link on the Panthers who played for the 1996 Stanley ",
        "Riders are propelled through the same boomerang configuration, except this ",
        "I found some unpublished passages that show how bin Laden's legacy is an ironic mix: His movement is largely destroyed, but his passion for a purer and more Islamic government in the Arab ",
        "The sixth-seeded Lancers advance to take on No. 2 seed Hazelwood ",
        "Send an ",
        "When it comes to tackling our own rehab for cardio-catastrophes, believe it or not, less than 20 percent of people who would benefit actually get with the ",
        "The 11-year-old Jersey City resident recently traveled to ESPN's Wide World of Sports at Walt Disney World in Orlando, ",
        "In the first home playoff game under new management, Sixers CEO Adam Aron said the pregame ",
        "Greenleaf officials said it signed leases in September and has wasted time and ",
        "If that happens, it's time to focus on something ",
        "Others were in pajama pants, looking as if they ran out the ",
        "That’s been an often-repeated assertion of Republican leaders like House Speaker ",
        "Only two countries that use the ",
        "\"There are alternatives out there that don't require these draconian cuts,\" he ",
        "License plates were stolen off a trailer Sunday in the 1300 ",
        "Chrysler CEO Sergio ",
        "We live in a place where the wonders of nature are never too far ",
        "(05-10) 13:01 PDT New York ",
        "Dugovich was right on the ",
        "The parking lot at the Udvar-Hazy Center will open at 8 a.m. for \"guaranteed viewing,\" said Valerie Neal, the National Air and ",
        "“Damsels in Distress,” Stillman’s first film in 14 years, moves his idiosyncratic drawing-room comedy to a dorm ",
        "No other injuries were ",
        "He is white Hispanic with hazel eyes and short black ",
        "Koschman died May 6, 2004, of brain injuries suffered when the punch to his face sent him reeling backward, and he cracked his head on the street on Division ",
        "“It was a very difficult two or ",
        "Briere recorded two goals, including the overtime game-winner, in Philadelphia's 4-3 win over New Jersey in Game 1 of the ",
        "“It has a ",
        "Some critics say the value-added ",
        "The Catholic hierarchy in Mexico also defended Maciel for many ",
        "\"Grimm\": Tonight's episode, \"Cat and Mouse,\" finds Monroe (Silas ",
        "\"This is one step in a comprehensive plan that could be happening in the next few years,\" she ",
        "The girls had six weeks to design and ",
        "As for the oysters themselves, he ",
        "“That says a lot about what players in this ",
        "Pacific Gas and Electric Co. workers who spent two days checking a natural-gas transmission line in Palo Alto for a leak detected during a high-pressure ",
        "\"The president and first lady reported a joint adjusted gross ",
        "Bridget Pickett said authorities continued to investigate what took place early Sunday in the ritzy Hancock Park neighborhood shortly after Brown and longtime girlfriend, pop superstar Rihanna, were seen happily sitting together at the annual pre-Grammy party hosted by Clive ",
        "Congress will make the final decision on ",
        "Those documents must be renewed at the ",
        "\"Judges should be held to higher standard every ",
        "The three New Jersey concerts are part of the 19-date tour that kicks off March 18 in Atlanta in support of Springsteen’s 17th studio album, \"Wrecking ",
        "Buffett thinks he should pay more taxes, even ",
        "Najibullah Zazi and Zarein Admedzay both pleaded guilty to conspiracy, and they took the witness ",
        "In addition to the 44 counties, city attorneys for Los ",
        "Eastern ",
        "\"It is a clearly illegal attempt to solve the ",
        "\"They promised fairness, they promised that we were all in it ",
        "Luke Daley said no ",
        "The UCLA-USC rift stretches through Southern ",
        "For more information, call Allen ",
        "It’s generally the grumblers who take the ",
        "\"It looked like the wind was ",
        "The Nasdaq composite index fell 0.29, or 0.01 ",
        "I think the fans of Miller feel a ",
        "Analysts, on average, were expecting an adjusted loss of 3 cents per share on ",
        "Also winning Saturday were the Fort Zumwalt ",
        "\"Not a lot of people take Arizona wine seriously,\" he ",
        "Manning’s hockey-like moment became the dominant story line on a night that began with these two franchises sharing the stage for the ",
        "TRENTON - A man was injured while diving for cover from a shooting outside a Greenwood Avenue gas station late last night, police ",
        "The White House started addressing climate ",
        "The untimely death of the game-changing rock 'n' roll guitarist is a central theme in Gregg Allman's life and a big part of the Rock and Roll Hall of ",
        "The Missouri Department of Natural ",
        "Beck went on to launch GBTV, a web-based television channel with more than 300,000 paying subscribers that some expect could generate more than $100 ",
        "Heat the oven to 350 ",
        "It was Roy’s first season in the five-year $82 million ",
        "Tomatoes and eggs were thrown at a home on the 12000 ",
        "Portland closed the first quarter on a 10-0 run and used a 12-3 run, capped by a buzzer beater from Roy, at the end of the second ",
        "\"I want to state loud and clear that I do not believe nor do I want the actions of a few to be representative of the ethical standards that each of ",
        "\"We really want to work something out with Metro,\" said Karen Holman, vice ",
        "Records ",
        "\"We were nervous — for a minute,\" said Nan Gartner, a retiree on her way to Italy from New York's John F. ",
        "Utah's law includes a provision to allow illegal ",
        "Stand Up Missouri, a group opposing the initiative with funding from companies in Texas, South Carolina, Mississippi and Oklahoma, says on its website that those organizing the petitions are made up of 'special interest ",
        "Highland junior Geoffrey Hartlieb led all ",
        "\"The Voice\" (Tuesday), NBC, 8.86 million ",
        "The companies had repeatedly offered to pay Cuyahoga ",
        "But you have a moral compass; the fact that this bothers you or that you're asking this ",
        "The Transit Riders Union advocates four things: Save Fareless Square, halt the cuts to bus service, elect the TriMet board of ",
        "Algeria's two government-allied party dominated parliamentary ",
        "To register, ",
        "\"Fifty years ago at the height of the civil-rights ",
        "Unfortunately, it will work to a certain ",
        "RT There's no place ",
        "Yea well being bored isn't fun.. but ",
        "I gotta 100 round drum ima rock n ",
        "Hope it's a ",
        "I don't need my oil ",
        "“: I love the taste of orange juice after I brush my ",
        "Not ",
        "Moving to LA in July so anyone looking to shoot let me ",
        "Running on like 3 hours of ",
        "But ",
        "Being dead broke is the root of all ",
        "I hope everything goes ",
        "#DONTTEXTANDDRIVE This Morning My Brothers Girlfriends Friend Died :/ from texting and driving she wasnt wearing a seat ",
        "5 days until KAHATF1HSWK!! :) I can't ",
        "Man no one tweets me ",
        "All these fairy tales are ",
        "Our Patio is ",
        "Wishing everyone a very Merry ",
        "That's a good rule of ",
        "I realize this will offend many of you, but ",
        "just woke up again xD sorry I didn't reply, I was working last ",
        "Sorry - Shiraz and Sexy Beast Cabernet Sauvignon Very ",
        "i knew i couldnt escape basketball i love it too ",
        "Still getting my hair ",
        "A wise man will listen to a fool, but a fool won't listen to a wise ",
        "Simba was walking too slow, so ",
        "Last game of the regular ",
        "#NP Ready-Frank Ocean I love this ",
        "i dare you to take credit for what i've done. you deserve every bit of it in a ",
        "Like most things in ",
        "Thank you so ",
        "It's lunch ",
        "This is why some people appear bright until you ",
        "Good things come to those who ",
        "Florida, you were fun. time to get ",
        "Thanks ; I will be doing that right ",
        "#Weather Cleveland, Ohio Weather :: 61F ",
        "Woop ",
        "Needy ass bxtches “: I want frozen ",
        "My mouth is ",
        "Complex..its a ",
        "All my bags are packed, I'm ready to ",
        "Normal messaging ",
        "RT : Can't ",
        "But ",
        "will begin tastings First tasting will take ",
        "Advertisements contain the only truths to be relied on in a newspaper. - Thomas ",
        "We would love it if you ReTweeted ",
        "Everyone have a great ",
        "One year anniversary arriving in the Emerald ",
        "Who brings me chick fil a with no chick ",
        "baby baby baby oh baby baby ",
        "Everytime ",
        "I realized life can pass you by if you don't enjoy the little things and let your self love and be ",
        "Now to apply the magic in the real ",
        "Sort of wish Celts had blown it up a ",
        "That's enough sudoku for the day , dontcha ",
        "please try adding a seattle ",
        "Great date movie without leaving the ",
        "I wish I did go all savage on my fridge/pantry right when I got ",
        "Friend us on Facebook to ",
        "I got my ",
        "Hope you're' doing ",
        "Now stop drop and roll Justin ",
        "dont really keep mayo on hand & was pleasantly ",
        "I think I'm the only one up right ",
        "Thank you for the follow - looking ",
        "I can't live ",
        "Well, at ",
        "maybe we just need to stop talking to other ",
        "= brush your ",
        "Or to put it another way - it's an effective ",
        "Scary ",
        "that had to be an awesome day in your ",
        "#CUBUFFS are gonna win this ",
        "Thank you :) RT Good luck to my pal He finally found Nemo, so tonight, ",
        "I need more followers I follow back ",
        "Forget about completing huge #dating profiles. is coming to our event next ",
        "To all our entrants in the recipe contest: share your recipe with your ",
        "RT : Working on my fantasy football ",
        "Listening to journalist talk about covering charter ",
        "But none of us can know what was ",
        "You're just somebody I used to ",
        "Im very lighted headed right ",
        "There is a song bout that indicating 5:00 is right.... but ",
        "Looking ",
        "OMG GUYZ MAX RETWEETED ME AM ",
        "Only my second year to Charleston, but found it useful last ",
        "Gonzalez out of lineup with strep ",
        "SF Symphony review: Baroque spirit soars - San ",
        "I'm not sure if ",
        "Speaking of which, ",
        "Hope you have a great ",
        "I think a lot of people didn't get the ",
        "You have 2561 followers on 5-16-2012 at 828pm Let's see what can be ",
        "RT : Say ths 2 yr children NOW: ",
        "While loving someone deeply gives you ",
        "The road to success is always under ",
        "In 100 euros he's been wanking off everytime ",
        "that's funny because I just screen shotted that and sent it to her 😂😂😂 let's see how much she ",
        "hope to ",
        "What is the world ",
        "But the good ",
        "I have nothing 2 do y am ",
        "There is so much talent here it makes me ",
        "I've been keeping an eye on it for the past two ",
        "“Live as if you were to die ",
        "Vermont bans hydraulic fracturing MONTPELIER , Vt. —Vermont became the first state in the ",
        "Foucault, on Deleuze: \"Do not think that one has to be sad in order to be militant, even ",
        "alrite ima hit u when I ",
        "The minute you settle for ",
        "Eyes that dont cry Lips that dont lie Love that wont ",
        "Happy ",
        "Visit a country where women are not given access to birth control. wld break your ",
        "Oh what would I do ",
        "Call us ",
        "So girl, keep ur ",
        "Oh man hopefully our wishes come ",
        "I know I've asked this before...but does anyone know of a ",
        "Plz ",
        "Normally, I flip cable news channels compulsively but, today C-SPAN-2 won out as my drug of ",
        "#lies sometimes it's hard to tell the ",
        "#AutismAwareness month is over but #AutismAwareness should not just be one month a ",
        "Never a dull ",
        "Gasol is on the back of a milk ",
        "If u be urself anything is ",
        "Next two nights off, i wanna have some ",
        "and thank you for your ",
        "I guess sometimes you don't realize how ",
        "Before New Years Eve Ends Will ",
        "Back in Atlanta and my bed is calling my ",
        "#Lauder exhibtion really made me want to get Great Collectors, but ",
        "I feel ",
        "I am in, sounds ",
        "This week has been so beautifully busy...busy ",
        "for a moment l'll add my new photos that ",
        "How is my freshman year of ",
        "I was just about to ",
        "That's what I'm ",
        "They don't make no ",
        "what's good fam, hope all is ",
        "I'm listening to king Kong right ",
        "I love it how I think theres no way u could be a bigger douchebag, then u go ahead & prove me ",
        "It makes me ",
        "Wishing you the very ",
        "Sick today, but no time to be sick, so I'm working from my bed when all I ",
        "Used to play floor hockey back in the ",
        "I do find it odd that a ",
        "Please let us ",
        "Union ",
        "We're giving ",
        "~Jim ",
        "RT : Before everything else, getting ready is the secret of success. -Henry ",
        "😡 lol glad I got to ",
        "I want to scratch my chest off right ",
        "carry yo ",
        "what brings you to this area of the ",
        "Nicki is so different, nobody ",
        "See you this ",
        "Follow me and I WILL follow back...for the most ",
        "\"I'm Todd Manning, you son of a ",
        "Is it too early to start making plans for this ",
        "yeah :) it's a small ",
        "Ball so ",
        "The only bad thing about the warm ",
        "Going to warped tour this ",
        "thanks Ernesto for kind mention- have a ",
        "great minds think alike :-) Merry ",
        "Seems interesting, good ",
        "Know I probably wouldn't get a ",
        "let ",
        "Lmaooo quotes this morn \"he wasn't with me shootin in the gym\" loll ",
        "perhaps, although giving an artsy cousin as a wedding ",
        "Is that too ",
        "#gettingoldsucks stick with beer away from liquor too ",
        "Yes, been a long ",
        "ok, well keep me ",
        "I do agree that money can't ",
        "Im cold & just want to go ",
        "Are you in College Station, ",
        "RT : Great reason 2 have social ",
        "This might be the best thing I've ",
        "i wish would follow me ",
        "Is the only genre of ",
        "Also, it would be interesting to ",
        "Corporations are ",
        "\"Take one for the ",
        "Pls take good ",
        "Friends listening to Boyfriend: He sounds ",
        "but aint nuffin like sitn in my panties and tshirt and recording...while munchin on chocolate chip ",
        "RT : Record Store ",
        "Get in ",
        "Looking ",
        "Teams who cut Jeremy Lin are feeling much ",
        "I can't watch it right ",
        "Iced caramel latte from Dunkin ",
        "When #moving - literary ephemera is one of the most difficult ",
        "Enjoy the gorgeous ",
        "Please ",
        "Had a great ",
        "If there's a cure for duckface, I'm betting it would be a ",
        "no I couldn't remember who she looked ",
        "oh, I think we all ",
        "Can't ",
        "Now we get to beat him twice a year in the regular ",
        "Adam was supposed to live 1,000 years, but sacrificed 70 years so that the eternal ",
        "It doesn't affect my ",
        "Great way to start the ",
        "Wedding planning is getting in the ",
        "What will they think of ",
        "Well, Wolf's been bad all year, but yeah, ",
        "thanks sweetheart- will miss you Friday & next ",
        "I love fashion and hip ",
        "We're giving away a DUCATI at #interop - stop by booth #1117 for a ",
        "Perfect day for making banana ",
        "Iyanze has the same owners as Bolat, so it's probably a ",
        "follow back beautiful and tell your friends to follow as ",
        "And I wanna say thank you incase I don't thank you ",
        "\"Obesity will crush the United ",
        "Yes, but even then, most of the ",
        "wht it is so i could check u n ",
        "Should be a ",
        "Tip 2: Refinement - Refinement exudes sophistication which implies education and ",
        "Education's purpose is to replace an empty mind with an open ",
        "Congratulations to the 2012 Ivy ",
        "Hard work is always rewarded one way or ",
        "he should ride a stationary ",
        "Getting ready to head back to Los Angeles thanks to everyone who ",
        "conquer local starbucks, go from there RT : I'm real, my ambitions for world ",
        "He has done so ",
        "I couldn't sleep because I was so ",
        "Glad you had a ",
        "I tweet about New ",
        "IM GETTING SOME OF YOUR MERCHANT :D :D :D ",
        "Also, bro-chela is no place for Jarvis ",
        "The principal figure in both photos was Jude ",
        "Sometimes I leave the ",
        "\": When breaking up, it's only polite to go out with a ",
        "Whose everybody got in the Kentucky ",
        "Just registered for Magic Live in Las ",
        "Thursday and ",
        "So seen a friend in a Hospital from being shot multiple ",
        "The years go by so ",
        "The pupperdoodle loves ice ",
        "Booze at Hair of the ",
        "I almost moved into a building at 15th and RI mostly so I could eat fried ",
        "Haven't watched either play much, but savvier Laker ",
        "back to class in the ",
        "Ethan said I don't tweet ",
        "DOES ANYONE WHO IS A MEMBER WANT TO NOMINATE ME SO ",
        "Thanks for the follow David, you guys rock the ",
        "can't wait for Millie's sausage and other amazing food this ",
        "Lol this necklace better change my ",
        "And my ",
        "Don't forget Josh Wilson can play left ",
        "Have a ",
        "This is your reminder to NOT click links that look ",
        "If a tomatoe is a ",
        "man I'm too blessed to be ",
        "So a couple weeks ago Justin was in Deerfield Beach AND I didn't know -_- he was on my beach and no ",
        "To be in the medical ",
        "We need to get together ",
        "RT \": Just stopping by to ",
        "I hate when people text me first and then don't keep the conversation ",
        "I haven't watched current season yet, but ",
        "That is irrelevant , you're ignorant either ",
        "Good to be ",
        "I feel like at the ",
        "I responded \"San ",
        ": I am so tired of dealing with ghetto ass shit, I done made some bad decisions in my ",
        "Interesting to ",
        "Follow me on ",
        "Believe me i do the same ",
        "I'm so ",
        "bought 1D tickets the other day for next year and i didnt tell my ",
        "23 days until my lazy days in Los ",
        "Also, ",
        "Rest is part of the healing ",
        "i made this account to ",
        "Work That Triangle Face ((: But No ",
        "RT : #Bears head coach Lovie ",
        "Time to get some work ",
        "It's hard to soar like an ",
        "or wearing a speedo in 55 degree ",
        "“: I need 52 more ",
        "This is how ",
        "Just loaded up all my files to my ",
        "hehe, great minds ",
        "because ",
        "\"It's never enough till your heart stops ",
        "I am always here if you would ",
        "Give the gift of good health this holiday ",
        "ok word see u when ",
        "Give a ",
        "A special welcome to my new ",
        "Why can't ",
        "A Question of Provenance - Vanity ",
        "Bummed ",
        "Happy Memorial ",
        "Love walking by Sophia's Heart on my way to the ",
        "IF I HAD #1WISH I WOULD LOVE IT IF U FOLLOWED ",
        "But ",
        "The cool story is gunna be me on the 5 o'clock ",
        "Please ",
        "Thank you, Any questions feel ",
        "Merry ",
        "I mean the score right ",
        "Is that what you really ",
        "Good thing ",
        "I miss my ex...but I honestly dont ",
        "(@ Chicago O'Hare International ",
        "Thanks to everyone who came out last ",
        "That's what ",
        "I wanna follow these stupid high ",
        "#ImThatPersonWho sticks up for my family no matter what the ",
        "I'm way too ",
        "i got my phone taken ",
        "Loved seeing tonight...been way too ",
        "Now ",
        "Looking at me now, I can see my past, Damn, I look just ",
        "Weber turned his ",
        "omg i wanna see you so badly when u come to ny but the meet and ",
        "The football game did not go so well as we lost 42-14, but ",
        "I wish Doris Burke would pull a junior seau right ",
        "Watched the Ten Commandments last night and had a ",
        "I Couldn't Even Answer Her Questions Cause ",
        "We appreciate you following Poised ",
        "Where would we be ",
        "Spending my afternoon at a Macomb ",
        "Wow, even in the city a little ",
        "Too ",
        "Dirk clearly has the ",
        "I'm so ready for the ",
        "Punk & the godfather by playing #strangetimes can't complain too "
    )
})
